-- MySQL Script generated by MySQL Workbench
-- Wed Mar 26 22:30:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema tsenane
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tsenane
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tsenane` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `tsenane`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`provinces` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tsenane`.`districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`districts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `provinceId` INT NOT NULL,
  `provinces_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`name` ASC) VISIBLE,
  INDEX `fk_districts_provinces1_idx` (`provinces_id` ASC) VISIBLE,
  CONSTRAINT `fk_districts_provinces1`
    FOREIGN KEY (`provinces_id`)
    REFERENCES `tsenane`.`provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 162
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`operators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsenane`.`bankAccounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`bankAccounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bankId` INT NOT NULL,
  `accountNumber` VARCHAR(100) NOT NULL,
  `companyId` VARCHAR(100) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `createdAt` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `accountNumber` (`accountNumber` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`system_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`system_suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `districts_id` INT NOT NULL,
  `operators_id` INT NOT NULL,
  `accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_system_suppliers_districts_idx` (`districts_id` ASC) VISIBLE,
  INDEX `fk_system_suppliers_operators1_idx` (`operators_id` ASC) VISIBLE,
  INDEX `fk_system_suppliers_accounts1_idx` (`accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_system_suppliers_districts`
    FOREIGN KEY (`districts_id`)
    REFERENCES `tsenane`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_suppliers_operators1`
    FOREIGN KEY (`operators_id`)
    REFERENCES `mydb`.`operators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_suppliers_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `tsenane`.`bankAccounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsenane`.`readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`readings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` VARCHAR(25) NOT NULL,
  `receiptNumber` INT NOT NULL,
  `uniqueBillId` VARCHAR(100) NOT NULL,
  `last` FLOAT NOT NULL DEFAULT '0',
  `current` FLOAT NULL DEFAULT '0',
  `consumption` FLOAT NOT NULL,
  `forfeit` FLOAT NOT NULL,
  `tarrifTypeId` INT NOT NULL,
  `branchId` INT NOT NULL,
  `month` INT NOT NULL,
  `year` INT NOT NULL,
  `takenAt` TEXT NOT NULL,
  `createdAt` TEXT NOT NULL,
  `dataEmissao` VARCHAR(25) NULL DEFAULT NULL,
  `dataLimite` VARCHAR(30) NULL DEFAULT NULL,
  `subTotal` FLOAT NULL DEFAULT NULL,
  `vat` FLOAT NULL DEFAULT NULL,
  `totalOfBill` FLOAT NULL DEFAULT NULL,
  `consumoFacturado` INT NULL DEFAULT '0',
  `consumptionPeriod` VARCHAR(25) NULL DEFAULT NULL,
  `staffName` VARCHAR(100) NULL DEFAULT NULL,
  `updatedBy` TEXT NULL DEFAULT NULL,
  `status` INT NOT NULL,
  `readingStatus` INT NOT NULL,
  `waterMeterImageUrl` TEXT NULL DEFAULT NULL,
  `lat` VARCHAR(45) NULL DEFAULT NULL,
  `lng` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniqueBillId` (`uniqueBillId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 96595
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tsenane`.`tarrifs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`tarrifs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tarrifTypeId` INT NOT NULL,
  `serviceAvailabilityFee` FLOAT NULL DEFAULT '0',
  `pricePerMeterCubic` FLOAT NULL DEFAULT '0',
  `socialTire` FLOAT NOT NULL,
  `firstFive` FLOAT NOT NULL,
  `firstSeven` FLOAT NULL DEFAULT '0',
  `aboveSeven` FLOAT NOT NULL,
  `firstFifteen` FLOAT NOT NULL,
  `aboveFifteen` FLOAT NOT NULL,
  `createdAt` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tarrifTypeId` (`tarrifTypeId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tsenane`.`tarrif_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`tarrif_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `tarrifs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarrif_type_tarrifs1_idx` (`tarrifs_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarrif_type_tarrifs1`
    FOREIGN KEY (`tarrifs_id`)
    REFERENCES `tsenane`.`tarrifs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`billing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` DATE NOT NULL,
  `readings_id` INT NOT NULL,
  `tarrif_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_billing_readings1_idx` (`readings_id` ASC) VISIBLE,
  INDEX `fk_billing_tarrif_type1_idx` (`tarrif_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_billing_readings1`
    FOREIGN KEY (`readings_id`)
    REFERENCES `tsenane`.`readings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_billing_tarrif_type1`
    FOREIGN KEY (`tarrif_type_id`)
    REFERENCES `tsenane`.`tarrif_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsenane`.`debts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`debts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` VARCHAR(50) NOT NULL,
  `readingId` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `tarrifTypeId` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL,
  `branchId` INT NOT NULL,
  `staffName` VARCHAR(100) NOT NULL,
  `createdAt` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12405
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tsenane`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customerName` VARCHAR(255) NOT NULL,
  `barcode` VARCHAR(50) NOT NULL,
  `tarrifTypeId` VARCHAR(50) NOT NULL,
  `totalPaid` FLOAT NOT NULL,
  `reference` VARCHAR(30) NOT NULL,
  `phoneNumber` TEXT NOT NULL,
  `smsDetails` TEXT NOT NULL,
  `staffName` VARCHAR(100) NOT NULL,
  `paymentMethod` INT NOT NULL,
  `dateOfPayment` VARCHAR(50) NOT NULL,
  `createdAt` VARCHAR(50) NULL DEFAULT NULL,
  `debts_id` INT NOT NULL,
  `readings_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reference` (`reference` ASC) VISIBLE,
  INDEX `fk_payments_debts1_idx` (`debts_id` ASC) VISIBLE,
  INDEX `fk_payments_readings1_idx` (`readings_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_debts1`
    FOREIGN KEY (`debts_id`)
    REFERENCES `tsenane`.`debts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_readings1`
    FOREIGN KEY (`readings_id`)
    REFERENCES `tsenane`.`readings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 86995
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`billing_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`billing_payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` DATE NOT NULL,
  `payments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_billing_payment_payments1_idx` (`payments_id` ASC) VISIBLE,
  CONSTRAINT `fk_billing_payment_payments1`
    FOREIGN KEY (`payments_id`)
    REFERENCES `tsenane`.`payments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `createdA` DATE NOT NULL,
  `tableName` VARCHAR(45) NOT NULL,
  `tableId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idaccessLevel_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles_has_permissions` (
  `roles_id` INT NOT NULL,
  `permissions_id` INT NOT NULL,
  PRIMARY KEY (`roles_id`, `permissions_id`),
  INDEX `fk_roles_has_permissions_permissions1_idx` (`permissions_id` ASC) VISIBLE,
  INDEX `fk_roles_has_permissions_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_has_permissions_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_permissions_permissions1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `mydb`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regulators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`regulators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operators_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idregulators_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_regulators_operators1_idx` (`operators_id` ASC) VISIBLE,
  CONSTRAINT `fk_regulators_operators1`
    FOREIGN KEY (`operators_id`)
    REFERENCES `mydb`.`operators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `tsenane` ;

-- -----------------------------------------------------
-- Table `tsenane`.`neighbourhoods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`neighbourhoods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyId` INT NOT NULL,
  `districtId` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `createdAt` VARCHAR(255) NOT NULL,
  `districts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branches_districts_idx` (`districts_id` ASC) VISIBLE,
  CONSTRAINT `fk_branches_districts`
    FOREIGN KEY (`districts_id`)
    REFERENCES `tsenane`.`districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 166
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tsenane`.`support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`support` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryType` INT NOT NULL,
  `fromNumber` VARCHAR(45) NOT NULL,
  `toNumber` VARCHAR(45) NOT NULL,
  `messageBody` LONGTEXT NOT NULL,
  `sentDateTime` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `customerName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tsenane`.`meters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`meters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meterNumber` VARCHAR(50) NOT NULL,
  `diameter` VARCHAR(15) NOT NULL,
  `description` TEXT NOT NULL,
  `status` INT NOT NULL DEFAULT '0',
  `createdAt` VARCHAR(100) NOT NULL,
  `readings_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `meterNumber` (`meterNumber` ASC) VISIBLE,
  INDEX `fk_meters_readings1_idx` (`readings_id` ASC) VISIBLE,
  CONSTRAINT `fk_meters_readings1`
    FOREIGN KEY (`readings_id`)
    REFERENCES `tsenane`.`readings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8156
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tsenane`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` VARCHAR(50) NULL DEFAULT NULL,
  `meeter_type` INT NOT NULL,
  `uid` TEXT NULL DEFAULT NULL,
  `branchId` INT NOT NULL,
  `tarrifTypeId` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `phone` VARCHAR(25) NOT NULL,
  `password` TEXT NOT NULL,
  `passwordHint` VARCHAR(255) NULL DEFAULT '0',
  `meeter_id` TEXT NOT NULL,
  `nuit` VARCHAR(15) NULL DEFAULT '0',
  `address` TEXT NULL DEFAULT NULL,
  `lat` VARCHAR(255) NULL DEFAULT NULL,
  `lng` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT NOT NULL,
  `whatsapp` INT NULL DEFAULT NULL,
  `appAndroid` INT NULL DEFAULT NULL,
  `readingStatus` INT NOT NULL DEFAULT '0',
  `createdAt` VARCHAR(100) NOT NULL,
  `support_id` INT NOT NULL,
  `meters_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `barcode` (`barcode` ASC) VISIBLE,
  INDEX `fk_customers_support1_idx` (`support_id` ASC) VISIBLE,
  INDEX `fk_customers_meters1_idx` (`meters_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_support1`
    FOREIGN KEY (`support_id`)
    REFERENCES `tsenane`.`support` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_meters1`
    FOREIGN KEY (`meters_id`)
    REFERENCES `tsenane`.`meters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9017
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tsenane`.`proforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`proforma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `invoiceId` INT NOT NULL,
  `preRegistrationId` VARCHAR(255) NOT NULL,
  `customerName` VARCHAR(255) NOT NULL,
  `customerAddress` TEXT NOT NULL,
  `customerPhoneNumber` INT NOT NULL,
  `customerNuit` INT NOT NULL,
  `customerEmail` VARCHAR(100) NOT NULL,
  `itemsDetails` TEXT NOT NULL,
  `staffName` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proforma_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_proforma_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `tsenane`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1755
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tsenane`.`pre_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`pre_registration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `nationalId` VARCHAR(45) NULL DEFAULT NULL,
  `nuit` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `createdAt` VARCHAR(45) NOT NULL,
  `proforma_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pre_registration_proforma1_idx` (`proforma_id` ASC) VISIBLE,
  CONSTRAINT `fk_pre_registration_proforma1`
    FOREIGN KEY (`proforma_id`)
    REFERENCES `tsenane`.`proforma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2235
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tsenane`.`prepaid_purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`prepaid_purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `barcode` VARCHAR(12) NOT NULL,
  `totalPaid` FLOAT NOT NULL,
  `totalUnities` FLOAT NOT NULL,
  `token` VARCHAR(50) NOT NULL,
  `receiptNumber` INT NOT NULL,
  `customerId` INT NOT NULL,
  `vat` FLOAT NOT NULL,
  `employeeId` VARCHAR(6) NOT NULL,
  `generatedDate` VARCHAR(100) NOT NULL,
  `paymentMethod` INT NOT NULL,
  `transactionId` VARCHAR(45) NOT NULL,
  `paidDebt` FLOAT NOT NULL,
  `debtBeforePurchase` FLOAT NOT NULL,
  `debtAfterPurchase` FLOAT NOT NULL,
  `amountValue` FLOAT NOT NULL,
  `customerName` VARCHAR(100) NOT NULL,
  `serviceAvailabilityFee` FLOAT NOT NULL,
  `staffName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tsenane`.`reportnotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`reportnotes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `staffName` VARCHAR(255) NOT NULL,
  `month` INT NOT NULL,
  `year` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tsenane`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` TEXT NOT NULL,
  `code` VARCHAR(15) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `password` TEXT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `userRole` INT NOT NULL,
  `branchId` INT NOT NULL,
  `companyId` INT NOT NULL,
  `status` INT NOT NULL,
  `createdAt` VARCHAR(255) NOT NULL,
  `token` TEXT NULL DEFAULT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phoneNumber` (`phoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_users_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 276
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tsenane`.`whatsapp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsenane`.`whatsapp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `barcode` VARCHAR(15) NOT NULL,
  `staffName` VARCHAR(45) NOT NULL,
  `status` INT NULL DEFAULT NULL,
  `createdAt` VARCHAR(45) NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_whatsapp_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_whatsapp_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `tsenane`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 805
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
